In [2]:
import matplotlib.pyplot as plt
import pandas as pd 
import matplotlib.font_manager
import numpy as np 
from scipy import stats
from pyod.models.abod import ABOD
from pyod.models.cblof import CBLOF
from pyod.models.feature_bagging import FeatureBagging
from pyod.models.hbos import HBOS
from pyod.models.iforest import IForest
from pyod.models.knn import KNN
from pyod.models.lof import LOF

/root/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)

In [5]:
dataset=pd.read_excel('ML_Project/player_playoff_career_avg.xlsx')

In [6]:
dataset.head()

,ilkid,firstname,lastname,ppts,pdreb,poreb,preb,pasts,pstl,pblk,pturnover,ppf,pfga,pfgm,pfta,pftm,ptpa,ptpm
0,ABDELAL01,Alaa,Abdelnaby,2.235294,1.000000,0.176471,1.176471,0.176471,0.000000,0.058824,0.647059,0.647059,2.352941,1.058824,0.235294,0.117647,0.000000,0.000000
1,ABDULKA01,Kareem,Abdul-jabbar,24.312236,3.514768,1.497890,10.468354,3.236287,0.632911,1.683544,1.704641,3.320675,18.658228,9.940928,5.987342,4.430380,0.016878,0.000000
2,ABDULMA01,Mahmo,Abdul-rauf,13.000000,1.200000,0.333333,1.533333,2.333333,0.466667,0.066667,1.466667,2.466667,12.466667,4.600000,3.000000,2.866667,3.266667,0.933333
3,ABDULTA01,Tariq,Abdul-wahad,5.230769,1.846154,1.307692,3.153846,0.846154,0.307692,0.307692,0.307692,1.076923,4.846154,1.846154,1.846154,1.538462,0.230769,0.000000
4,ABERNTO01,Tom,Abernethy,5.230769,0.000000,0.000000,3.230769,1.769231,0.000000,0.000000,0.000000,1.384615,4.153846,1.692308,2.230769,1.846154,0.000000,0.000000